spring:
  profiles: cat
server:
  port: 20001
  servlet:
    context-path: /shield
eureka:
  instance:
    hostname: cat
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    service-url:
      defaultZone: http://cat:20001/shield/eureka,http://dog:20002/shield/eureka